# Site settings
title: Tyler's Blog
header-img: img/home-bg.jpg
email: tyler@drombosky.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://tyler.drombosky.com"
twitter_username: drombosky
github_username:  drombosky

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
